[package]
name = "web"
version = "0.1.0"
authors = ["Atul Varma <varmaa@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
bmp = "0.5.0"
csolib = { path = "../csolib" }
wasm-bindgen = "0.2.72"
